# Generated by Django 4.2.7 on 2024-01-13 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classdata',
            old_name='classname',
            new_name='metadata',
        ),
    ]
